import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerSayHelloTool } from "./say_hello.js";
import { registerGetElementParametersTool } from "./get_element_parameters.js";
import { registerAIElementFilterTool } from "./ai_element_filter.js";
import { registerSetElementParametersTool } from "./set_element_parameters.js";
import { registerGetSelectedElementsTool } from "./get_selected_elements.js";
import { registerGetCurrentViewElementsTool } from "./get_current_view_elements.js";
import { registerGetLinkedElementsTool } from "./get_linked_elements.js";
import { registerGetElementsInSpatialVolumeTool } from "./get_elements_in_spatial_volume.js";
import { registerDeleteElementTool } from "./delete_element.js";
import { registerOperateElementTool } from "./operate_element.js";
import { registerChangeElementTypeTool } from "./change_element_type.js";
import { registerModifyElementTool } from "./modify_element.js";
import { registerCopyElementsTool } from "./copy_elements.js";
import { registerMeasureBetweenElementsTool } from "./measure_between_elements.js";
import { registerRenumberElementsTool } from "./renumber_elements.js";
import { registerFindUntaggedElementsTool } from "./find_untagged_elements.js";
import { registerFindUndimensionedElementsTool } from "./find_undimensioned_elements.js";
import { registerExportElementsDataTool } from "./export_elements_data.js";
import { registerMatchElementPropertiesTool } from "./match_element_properties.js";
import { registerCreateLineBasedElementTool } from "./create_line_based_element.js";
import { registerCreatePointBasedElementTool } from "./create_point_based_element.js";
import { registerCreateSurfaceBasedElementTool } from "./create_surface_based_element.js";
import { registerSetElementPhaseTool } from "./set_element_phase.js";
import { registerSetElementWorksetTool } from "./set_element_workset.js";
import { registerColorElementsTool } from "./color_elements.js";
import { registerGetProjectInfoTool } from "./get_project_info.js";
import { registerGetPhasesTool } from "./get_phases.js";
import { registerGetWorksetsTool } from "./get_worksets.js";
import { registerGetWarningsTool } from "./get_warnings.js";
import { registerGetCurrentViewInfoTool } from "./get_current_view_info.js";
import { registerFilterByParameterValueTool } from "./filter_by_parameter_value.js";
import { registerGetMaterialsTool } from "./get_materials.js";
import { registerGetMaterialPropertiesTool } from "./get_material_properties.js";
import { registerGetMaterialQuantitiesTool } from "./get_material_quantities.js";
import { registerGetScheduleDataTool } from "./get_schedule_data.js";
import { registerGetSharedParametersTool } from "./get_shared_parameters.js";
import { registerListSchedulableFieldsTool } from "./list_schedulable_fields.js";
import { registerGetAvailableFamilyTypesTool } from "./get_available_family_types.js";
import { registerListFamilySizesTool } from "./list_family_sizes.js";
import { registerLinesPerViewCountTool } from "./lines_per_view_count.js";
import { registerGetRoomOpeningsTool } from "./get_room_openings.js";
import { registerCreateDimensionsTool } from "./create_dimensions.js";
import { registerCreateTextNoteTool } from "./create_text_note.js";
import { registerCreateColorLegendTool } from "./create_color_legend.js";
import { registerImportTableTool } from "./import_table.js";
import { registerAddSharedParameterTool } from "./add_shared_parameter.js";
import { registerManageProjectParametersTool } from "./manage_project_parameters.js";
import { registerAddPrefixSuffixTool } from "./add_prefix_suffix.js";
import { registerCreateFloorTool } from "./create_floor.js";
import { registerCreateGridTool } from "./create_grid.js";
import { registerCreateLevelTool } from "./create_level.js";
import { registerCreateRoomTool } from "./create_room.js";
import { registerCreateArrayTool } from "./create_array.js";
import { registerCreateFilledRegionTool } from "./create_filled_region.js";
import { registerCreateScheduleTool } from "./create_schedule.js";
import { registerCreateSheetTool } from "./create_sheet.js";
import { registerCreateRevisionTool } from "./create_revision.js";
import { registerTagRoomsTool } from "./tag_rooms.js";
import { registerTagWallsTool } from "./tag_walls.js";
import { registerSaveSelectionTool } from "./save_selection.js";
import { registerLoadSelectionTool } from "./load_selection.js";
import { registerDeleteSelectionTool } from "./delete_selection.js";
import { registerApplyViewTemplateTool } from "./apply_view_template.js";
import { registerBatchModifyViewRangeTool } from "./batch_modify_view_range.js";
import { registerCreateViewTool } from "./create_view.js";
import { registerDuplicateViewTool } from "./duplicate_view.js";
import { registerCreateViewFilterTool } from "./create_view_filter.js";
import { registerOverrideGraphicsTool } from "./override_graphics.js";
import { registerPlaceViewportTool } from "./place_viewport.js";
import { registerSectionBoxFromSelectionTool } from "./section_box_from_selection.js";
import { registerManageUnplacedViewsTool } from "./manage_unplaced_views.js";
import { registerManageViewTemplatesTool } from "./manage_view_templates.js";
import { registerCreateViewsFromRoomsTool } from "./create_views_from_rooms.js";
import { registerAlignViewportsTool } from "./align_viewports.js";
import { registerBatchCreateSheetsTool } from "./batch_create_sheets.js";
import { registerCreatePlaceholderSheetsTool } from "./create_placeholder_sheets.js";
import { registerDuplicateSheetWithContentTool } from "./duplicate_sheet_with_content.js";
import { registerDuplicateSheetWithViewsTool } from "./duplicate_sheet_with_views.js";
import { registerBulkModifyParameterValuesTool } from "./bulk_modify_parameter_values.js";
import { registerClearParameterValuesTool } from "./clear_parameter_values.js";
import { registerTransferParametersTool } from "./transfer_parameters.js";
import { registerSetMaterialPropertiesTool } from "./set_material_properties.js";
import { registerBatchRenameTool } from "./batch_rename.js";
import { registerLoadFamilyTool } from "./load_family.js";
import { registerRenameFamiliesTool } from "./rename_families.js";
import { registerRenameViewsTool } from "./rename_views.js";
import { registerManageLinksTool } from "./manage_links.js";
import { registerGetLinkedFileInstancesTool } from "./get_linked_file_instances.js";
import { registerGetLinkTransformTool } from "./get_link_transform.js";
import { registerReloadLinkedFileFromTool } from "./reload_linked_file_from.js";
import { registerAddLinkedFileTool } from "./add_linked_file.js";
import { registerPinUnpinLinkInstanceTool } from "./pin_unpin_link_instance.js";
import { registerMoveLinkInstanceTool } from "./move_link_instance.js";
import { registerAlignLinkToHostTool } from "./align_link_to_host.js";
import { registerHighlightLinkedElementTool } from "./highlight_linked_element.js";
import { registerGetSelectedLinkedElementsTool } from "./get_selected_linked_elements.js";
import { registerSendCodeToRevitTool } from "./send_code_to_revit.js";
import { registerWipeEmptyTagsTool } from "./wipe_empty_tags.js";
import { registerAnalyzeModelStatisticsTool } from "./analyze_model_statistics.js";
import { registerCheckModelHealthTool } from "./check_model_health.js";
import { registerAuditFamiliesTool } from "./audit_families.js";
import { registerPurgeUnusedTool } from "./purge_unused.js";
import { registerCadLinkCleanupTool } from "./cad_link_cleanup.js";
import { registerClashDetectionTool } from "./clash_detection.js";
import { registerExportRoomDataTool } from "./export_room_data.js";
import { registerExportScheduleTool } from "./export_schedule.js";
import { registerDeleteScheduleTool } from "./delete_schedule.js";
import { registerDuplicateScheduleTool } from "./duplicate_schedule.js";
import { registerModifyScheduleTool } from "./modify_schedule.js";
import { registerCreatePresetScheduleTool } from "./create_preset_schedule.js";
import { registerExportFamiliesTool } from "./export_families.js";
import { registerExportSharedParameterFileTool } from "./export_shared_parameter_file.js";
import { registerCreateStructuralFramingSystemTool } from "./create_structural_framing_system.js";
import { registerSyncCsvParametersTool } from "./sync_csv_parameters.js";
import { registerBatchExportTool } from "./batch_export.js";
import { registerExportToExcelTool } from "./export_to_excel.js";
import { registerImportFromExcelTool } from "./import_from_excel.js";
import { registerWorkflowClashReviewTool } from "./workflow_clash_review.js";
import { registerWorkflowRoomDocumentationTool } from "./workflow_room_documentation.js";
import { registerWorkflowSheetSetTool } from "./workflow_sheet_set.js";
import { registerWorkflowModelAuditTool } from "./workflow_model_audit.js";
import { registerWorkflowDataRoundtripTool } from "./workflow_data_roundtrip.js";
import { registerStoreProjectDataTool } from "./store_project_data.js";
import { registerStoreRoomDataTool } from "./store_room_data.js";
import { registerQueryStoredDataTool } from "./query_stored_data.js";
import { registerAnalyzeJournalTool } from "./analyze_journal.js";
import { registerCreateMaterialTool } from "./create_material.js";
import { registerDuplicateMaterialTool } from "./duplicate_material.js";
import { registerDeleteMaterialTool } from "./delete_material.js";
import { registerGetCompoundStructureTool } from "./get_compound_structure.js";
import { registerSetCompoundStructureTool } from "./set_compound_structure.js";
import { registerDuplicateSystemTypeTool } from "./duplicate_system_type.js";
import { registerDuplicateFamilyTypeTool } from "./duplicate_family_type.js";
import { registerReportTokenUsageTool } from "./report_token_usage.js";
import { registerIfcGetCapabilitiesTool } from "./ifc_get_capabilities.js";
import { registerIfcValidateRequestTool } from "./ifc_validate_request.js";
import { registerIfcLinkTool } from "./ifc_link.js";
import { registerIfcReloadLinkTool } from "./ifc_reload_link.js";
import { registerIfcOpenOrImportTool } from "./ifc_open_or_import.js";
import { registerIfcExportBasicTool } from "./ifc_export_basic.js";
import { registerIfcExportWithConfigurationTool } from "./ifc_export_with_configuration.js";
import { registerIfcListExportConfigurationsTool } from "./ifc_list_export_configurations.js";
import { registerIfcGetExportConfigurationTool } from "./ifc_get_export_configuration.js";
import { registerIfcSetFamilyMappingFileTool } from "./ifc_set_family_mapping_file.js";
import { logInfo } from "../logging/logger.js";

const toolRegistrations: Array<{ name: string; register: (s: McpServer) => void }> = [
  { name: "say_hello", register: registerSayHelloTool },
  { name: "get_element_parameters", register: registerGetElementParametersTool },
  { name: "ai_element_filter", register: registerAIElementFilterTool },
  { name: "set_element_parameters", register: registerSetElementParametersTool },
  { name: "get_selected_elements", register: registerGetSelectedElementsTool },
  { name: "get_current_view_elements", register: registerGetCurrentViewElementsTool },
  { name: "get_linked_elements", register: registerGetLinkedElementsTool },
  { name: "get_elements_in_spatial_volume", register: registerGetElementsInSpatialVolumeTool },
  { name: "delete_element", register: registerDeleteElementTool },
  { name: "operate_element", register: registerOperateElementTool },
  { name: "change_element_type", register: registerChangeElementTypeTool },
  { name: "modify_element", register: registerModifyElementTool },
  { name: "copy_elements", register: registerCopyElementsTool },
  { name: "measure_between_elements", register: registerMeasureBetweenElementsTool },
  { name: "renumber_elements", register: registerRenumberElementsTool },
  { name: "find_untagged_elements", register: registerFindUntaggedElementsTool },
  { name: "find_undimensioned_elements", register: registerFindUndimensionedElementsTool },
  { name: "export_elements_data", register: registerExportElementsDataTool },
  { name: "match_element_properties", register: registerMatchElementPropertiesTool },
  { name: "create_line_based_element", register: registerCreateLineBasedElementTool },
  { name: "create_point_based_element", register: registerCreatePointBasedElementTool },
  { name: "create_surface_based_element", register: registerCreateSurfaceBasedElementTool },
  { name: "set_element_phase", register: registerSetElementPhaseTool },
  { name: "set_element_workset", register: registerSetElementWorksetTool },
  { name: "color_elements", register: registerColorElementsTool },
  { name: "get_project_info", register: registerGetProjectInfoTool },
  { name: "get_phases", register: registerGetPhasesTool },
  { name: "get_worksets", register: registerGetWorksetsTool },
  { name: "get_warnings", register: registerGetWarningsTool },
  { name: "get_current_view_info", register: registerGetCurrentViewInfoTool },
  { name: "filter_by_parameter_value", register: registerFilterByParameterValueTool },
  { name: "get_materials", register: registerGetMaterialsTool },
  { name: "get_material_properties", register: registerGetMaterialPropertiesTool },
  { name: "get_material_quantities", register: registerGetMaterialQuantitiesTool },
  { name: "get_schedule_data", register: registerGetScheduleDataTool },
  { name: "get_shared_parameters", register: registerGetSharedParametersTool },
  { name: "list_schedulable_fields", register: registerListSchedulableFieldsTool },
  { name: "get_available_family_types", register: registerGetAvailableFamilyTypesTool },
  { name: "list_family_sizes", register: registerListFamilySizesTool },
  { name: "lines_per_view_count", register: registerLinesPerViewCountTool },
  { name: "get_room_openings", register: registerGetRoomOpeningsTool },
  { name: "create_dimensions", register: registerCreateDimensionsTool },
  { name: "create_text_note", register: registerCreateTextNoteTool },
  { name: "create_color_legend", register: registerCreateColorLegendTool },
  { name: "import_table", register: registerImportTableTool },
  { name: "add_shared_parameter", register: registerAddSharedParameterTool },
  { name: "manage_project_parameters", register: registerManageProjectParametersTool },
  { name: "add_prefix_suffix", register: registerAddPrefixSuffixTool },
  { name: "create_floor", register: registerCreateFloorTool },
  { name: "create_grid", register: registerCreateGridTool },
  { name: "create_level", register: registerCreateLevelTool },
  { name: "create_room", register: registerCreateRoomTool },
  { name: "create_array", register: registerCreateArrayTool },
  { name: "create_filled_region", register: registerCreateFilledRegionTool },
  { name: "create_schedule", register: registerCreateScheduleTool },
  { name: "create_sheet", register: registerCreateSheetTool },
  { name: "create_revision", register: registerCreateRevisionTool },
  { name: "tag_rooms", register: registerTagRoomsTool },
  { name: "tag_walls", register: registerTagWallsTool },
  { name: "save_selection", register: registerSaveSelectionTool },
  { name: "load_selection", register: registerLoadSelectionTool },
  { name: "delete_selection", register: registerDeleteSelectionTool },
  { name: "apply_view_template", register: registerApplyViewTemplateTool },
  { name: "batch_modify_view_range", register: registerBatchModifyViewRangeTool },
  { name: "create_view", register: registerCreateViewTool },
  { name: "duplicate_view", register: registerDuplicateViewTool },
  { name: "create_view_filter", register: registerCreateViewFilterTool },
  { name: "override_graphics", register: registerOverrideGraphicsTool },
  { name: "place_viewport", register: registerPlaceViewportTool },
  { name: "section_box_from_selection", register: registerSectionBoxFromSelectionTool },
  { name: "manage_unplaced_views", register: registerManageUnplacedViewsTool },
  { name: "manage_view_templates", register: registerManageViewTemplatesTool },
  { name: "create_views_from_rooms", register: registerCreateViewsFromRoomsTool },
  { name: "align_viewports", register: registerAlignViewportsTool },
  { name: "batch_create_sheets", register: registerBatchCreateSheetsTool },
  { name: "create_placeholder_sheets", register: registerCreatePlaceholderSheetsTool },
  { name: "duplicate_sheet_with_content", register: registerDuplicateSheetWithContentTool },
  { name: "duplicate_sheet_with_views", register: registerDuplicateSheetWithViewsTool },
  { name: "bulk_modify_parameter_values", register: registerBulkModifyParameterValuesTool },
  { name: "clear_parameter_values", register: registerClearParameterValuesTool },
  { name: "transfer_parameters", register: registerTransferParametersTool },
  { name: "set_material_properties", register: registerSetMaterialPropertiesTool },
  { name: "batch_rename", register: registerBatchRenameTool },
  { name: "load_family", register: registerLoadFamilyTool },
  { name: "rename_families", register: registerRenameFamiliesTool },
  { name: "rename_views", register: registerRenameViewsTool },
  { name: "manage_links", register: registerManageLinksTool },
  { name: "get_linked_file_instances", register: registerGetLinkedFileInstancesTool },
  { name: "get_link_transform", register: registerGetLinkTransformTool },
  { name: "reload_linked_file_from", register: registerReloadLinkedFileFromTool },
  { name: "add_linked_file", register: registerAddLinkedFileTool },
  { name: "pin_unpin_link_instance", register: registerPinUnpinLinkInstanceTool },
  { name: "move_link_instance", register: registerMoveLinkInstanceTool },
  { name: "align_link_to_host", register: registerAlignLinkToHostTool },
  { name: "highlight_linked_element", register: registerHighlightLinkedElementTool },
  { name: "get_selected_linked_elements", register: registerGetSelectedLinkedElementsTool },
  { name: "send_code_to_revit", register: registerSendCodeToRevitTool },
  { name: "wipe_empty_tags", register: registerWipeEmptyTagsTool },
  { name: "analyze_model_statistics", register: registerAnalyzeModelStatisticsTool },
  { name: "check_model_health", register: registerCheckModelHealthTool },
  { name: "audit_families", register: registerAuditFamiliesTool },
  { name: "purge_unused", register: registerPurgeUnusedTool },
  { name: "cad_link_cleanup", register: registerCadLinkCleanupTool },
  { name: "clash_detection", register: registerClashDetectionTool },
  { name: "export_room_data", register: registerExportRoomDataTool },
  { name: "export_schedule", register: registerExportScheduleTool },
  { name: "delete_schedule", register: registerDeleteScheduleTool },
  { name: "duplicate_schedule", register: registerDuplicateScheduleTool },
  { name: "modify_schedule", register: registerModifyScheduleTool },
  { name: "create_preset_schedule", register: registerCreatePresetScheduleTool },
  { name: "export_families", register: registerExportFamiliesTool },
  { name: "export_shared_parameter_file", register: registerExportSharedParameterFileTool },
  { name: "create_structural_framing_system", register: registerCreateStructuralFramingSystemTool },
  { name: "sync_csv_parameters", register: registerSyncCsvParametersTool },
  { name: "batch_export", register: registerBatchExportTool },
  { name: "export_to_excel", register: registerExportToExcelTool },
  { name: "import_from_excel", register: registerImportFromExcelTool },
  { name: "workflow_clash_review", register: registerWorkflowClashReviewTool },
  { name: "workflow_room_documentation", register: registerWorkflowRoomDocumentationTool },
  { name: "workflow_sheet_set", register: registerWorkflowSheetSetTool },
  { name: "workflow_model_audit", register: registerWorkflowModelAuditTool },
  { name: "workflow_data_roundtrip", register: registerWorkflowDataRoundtripTool },
  { name: "store_project_data", register: registerStoreProjectDataTool },
  { name: "store_room_data", register: registerStoreRoomDataTool },
  { name: "query_stored_data", register: registerQueryStoredDataTool },
  { name: "analyze_journal", register: registerAnalyzeJournalTool },
  { name: "create_material", register: registerCreateMaterialTool },
  { name: "duplicate_material", register: registerDuplicateMaterialTool },
  { name: "delete_material", register: registerDeleteMaterialTool },
  { name: "get_compound_structure", register: registerGetCompoundStructureTool },
  { name: "set_compound_structure", register: registerSetCompoundStructureTool },
  { name: "duplicate_system_type", register: registerDuplicateSystemTypeTool },
  { name: "duplicate_family_type", register: registerDuplicateFamilyTypeTool },
  { name: "report_token_usage", register: registerReportTokenUsageTool },
  { name: "ifc_get_capabilities", register: registerIfcGetCapabilitiesTool },
  { name: "ifc_validate_request", register: registerIfcValidateRequestTool },
  { name: "ifc_link", register: registerIfcLinkTool },
  { name: "ifc_reload_link", register: registerIfcReloadLinkTool },
  { name: "ifc_open_or_import", register: registerIfcOpenOrImportTool },
  { name: "ifc_export_basic", register: registerIfcExportBasicTool },
  { name: "ifc_export_with_configuration", register: registerIfcExportWithConfigurationTool },
  { name: "ifc_list_export_configurations", register: registerIfcListExportConfigurationsTool },
  { name: "ifc_get_export_configuration", register: registerIfcGetExportConfigurationTool },
  { name: "ifc_set_family_mapping_file", register: registerIfcSetFamilyMappingFileTool },
];

export function registerTools(server: McpServer): void {
  for (const { name, register } of toolRegistrations) {
    try {
      register(server);
      logInfo(`Registered tool: ${name}`);
    } catch (error) {
      logInfo(`Failed to register tool ${name}: ${error}`);
    }
  }
  logInfo(`Total tools registered: ${toolRegistrations.length}`);
}
