using System.Text.RegularExpressions;
using RevitCortex.Core.Results;
using RevitCortex.Core.Security;

namespace RevitCortex.Tools.Dynamo.Security
{
    /// <summary>
    /// Validates generated Python before it is written into a .dyn. Two layers:
    /// (1) a Python-aware pre-check for forbidden namespaces smuggled inside
    ///     clr.AddReference("...") / import statements (CodeSandboxV2 blanks string
    ///     literals, so it cannot see a namespace that appears only inside a quoted argument);
    /// (2) delegation to the shared CodeSandbox (send_code_to_revit parity) for bare refs.
    /// Returns null when clean. Guards the automated AI-&gt;generate-&gt;run channel only;
    /// a user who opens the .dyn by hand can still run anything.
    /// </summary>
    public static class PythonSandbox
    {
        // Same intent as CodeSandboxV2.ProhibitedNamespaces, adapted for Python/IronPython:
        // CodeSandboxV2 lists "System.Diagnostics.Process" (C# usage is Process.Start), but
        // idiomatic Dynamo Python writes `import System.Diagnostics` / `clr.AddReference('System.Diagnostics')`,
        // so we block on the "System.Diagnostics" prefix to still catch Process.
        private static readonly string[] ForbiddenNamespaces =
        {
            "System.IO",
            "System.Net",
            "System.Diagnostics",
            "Microsoft.Win32",
            "System.Reflection",   // covers .Emit too
            "System.Runtime.InteropServices"
        };

        public static CortexResult<object>? Validate(string pythonCode)
        {
            var code = pythonCode ?? "";

            // Layer 1: namespaces referenced ANYWHERE, including inside string literals.
            // We scan the RAW code (do NOT strip strings) for each forbidden namespace token
            // as a whole dotted identifier. This catches clr.AddReference("System.IO"),
            // clr.AddReferenceToFileAndPath("...System.Net..."), import System.IO,
            // from System.Net import X, etc. — all of which CodeSandboxV2 misses when the
            // namespace only appears inside the quoted argument.
            foreach (var ns in ForbiddenNamespaces)
            {
                // Preceding boundary: start of string, or any char that is not a word char or '.'
                // (so "System.IO" inside "MySystem.IO" or "System.ION" won't match).
                // Trailing boundary: end of string, or any char that is not a word char
                // ('.' is allowed after, so "System.Reflection.Emit" still matches "System.Reflection").
                var pattern = @"(^|[^\w.])" + Regex.Escape(ns) + @"($|[^\w])";
                if (Regex.IsMatch(code, pattern))
                {
                    return CortexResult<object>.Fail(
                        CortexErrorCode.PermissionDenied,
                        "Python references the forbidden namespace '" + ns + "'. Dynamo Python generated by RevitCortex cannot use filesystem, network, process, registry, reflection-emit, or interop APIs.",
                        suggestion: "Use only the Revit API and safe computation. To run file/network operations, open the generated .dyn in Dynamo manually and take responsibility for it, or ask the user to enable an unsandboxed path.");
                }
            }

            // Layer 2: bare-reference / pattern checks shared with send_code_to_revit.
            return CodeSandbox.Validate(code);
        }
    }
}
