using System.Text.RegularExpressions;
using RevitCortex.Core.Results;
using RevitCortex.Core.Security;

namespace RevitCortex.Tools.Dynamo.Security
{
    /// <summary>
    /// Validates generated Python before it is written into a .dyn. Two layers:
    /// (1) a Python-aware pre-check for forbidden namespaces smuggled inside
    ///     clr.AddReference("...") / import statements (CodeSandboxV2 blanks string
    ///     literals, so it cannot see a namespace that appears only inside a quoted argument);
    /// (2) delegation to the shared CodeSandbox (send_code_to_revit parity) for bare refs.
    /// Returns null when clean. Guards the automated AI-&gt;generate-&gt;run channel only;
    /// a user who opens the .dyn by hand can still run anything.
    /// </summary>
    public static class PythonSandbox
    {
        // Same intent as CodeSandboxV2.ProhibitedNamespaces, adapted for Python/IronPython:
        // CodeSandboxV2 lists "System.Diagnostics.Process" (C# usage is Process.Start), but
        // idiomatic Dynamo Python writes `import System.Diagnostics` / `clr.AddReference('System.Diagnostics')`,
        // so we block on the "System.Diagnostics" prefix to still catch Process.
        private static readonly string[] ForbiddenNamespaces =
        {
            "System.IO",
            "System.Net",
            "System.Diagnostics",
            "Microsoft.Win32",
            "System.Reflection",   // covers .Emit too
            "System.Runtime.InteropServices"
        };

        // Python dynamic-dispatch / code-gen primitives. These let generated code reach a
        // forbidden namespace or member by name-building (getattr(io, "Fi"+"le")) or execute
        // an arbitrary string (eval/exec/compile), sidestepping both the raw-namespace scan
        // (no contiguous forbidden token exists) and CodeSandboxV2 (its reflection patterns are
        // C#-shaped: Type.GetType/.Invoke/dynamic — none match the Python equivalents).
        // This is PARITY with the C# reflection blocks Layer 2 already enforces. RevitCortex
        // GENERATES this Python and never legitimately needs dynamic dispatch, so blocking is safe.
        // getattr/setattr/__import__/eval/exec/compile/__getattribute__ are the hard must-blocks.
        private static readonly string[] DynamicDispatchPrimitives =
        {
            "getattr",
            "setattr",
            "delattr",
            "__import__",
            "eval",
            "exec",
            "compile",
            "__getattribute__"
        };

        public static CortexResult<object>? Validate(string pythonCode)
        {
            var code = pythonCode ?? "";

            // Layer 1: namespaces referenced ANYWHERE, including inside string literals.
            // We scan the RAW code (do NOT strip strings) for each forbidden namespace token
            // as a whole dotted identifier. This catches clr.AddReference("System.IO"),
            // clr.AddReferenceToFileAndPath("...System.Net..."), import System.IO,
            // from System.Net import X, etc. — all of which CodeSandboxV2 misses when the
            // namespace only appears inside the quoted argument.
            foreach (var ns in ForbiddenNamespaces)
            {
                // Preceding boundary: start of string, or any char that is not a word char or '.'
                // (so "System.IO" inside "MySystem.IO" or "System.ION" won't match).
                // Trailing boundary: end of string, or any char that is not a word char
                // ('.' is allowed after, so "System.Reflection.Emit" still matches "System.Reflection").
                var pattern = @"(^|[^\w.])" + Regex.Escape(ns) + @"($|[^\w])";
                if (Regex.IsMatch(code, pattern))
                {
                    return CortexResult<object>.Fail(
                        CortexErrorCode.PermissionDenied,
                        "Python references the forbidden namespace '" + ns + "'. Dynamo Python generated by RevitCortex cannot use filesystem, network, process, registry, reflection-emit, or interop APIs.",
                        suggestion: "Use only the Revit API and safe computation. To run file/network operations, open the generated .dyn in Dynamo manually and take responsibility for it, or ask the user to enable an unsandboxed path.");
                }
            }

            // Layer 1b: dynamic-dispatch / code-gen primitive block (RAW code).
            // Match the CALL form only — identifier at a boundary, followed by optional
            // whitespace and '('. The leading (^|[^\w.]) boundary prevents matching a
            // substring of a longer identifier (e.g. a variable named getattr_result, or
            // obj.eval) while still catching bare `getattr(`, `eval (`, `__import__(`.
            foreach (var prim in DynamicDispatchPrimitives)
            {
                var pattern = @"(^|[^\w.])" + Regex.Escape(prim) + @"\s*\(";
                if (Regex.IsMatch(code, pattern))
                {
                    return CortexResult<object>.Fail(
                        CortexErrorCode.PermissionDenied,
                        "Python dynamic dispatch / code-gen primitive '" + prim + "' is not allowed in RevitCortex-generated graphs.",
                        suggestion: "Generated Dynamo Python must use direct, statically-visible API calls. Dynamic name-building or arbitrary code execution (getattr/setattr/__import__/eval/exec/compile) can bypass the namespace sandbox and is prohibited.");
                }
            }

            // Layer 1c: non-literal clr.AddReference argument block (RAW code, line-scoped).
            // A legitimate generated reference is always a single string literal
            // (clr.AddReference('RevitAPI')). A concatenated argument
            // (clr.AddReference('System.' + 'IO')) exists only to smuggle a forbidden
            // namespace past the contiguous-token scan, so we block any AddReference /
            // AddReferenceToFileAndPath call that has a '+' on the same statement line.
            // Line-scoping avoids over-matching a '+' that appears elsewhere in the file.
            foreach (var line in code.Split('\n'))
            {
                if (line.IndexOf("AddReference", System.StringComparison.Ordinal) >= 0 &&
                    line.IndexOf('+') >= 0)
                {
                    return CortexResult<object>.Fail(
                        CortexErrorCode.PermissionDenied,
                        "clr.AddReference with a non-literal (concatenated) argument is not allowed — use a single string literal.",
                        suggestion: "Reference assemblies by their exact name as one string literal, e.g. clr.AddReference('RevitAPI'). A split/concatenated reference name is treated as an attempt to smuggle a forbidden namespace past the sandbox.");
                }
            }

            // Layer 2: bare-reference / pattern checks shared with send_code_to_revit.
            return CodeSandbox.Validate(code);
        }
    }
}
